Shoppy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('products.urls', namespace='products')),
    url(r'^', include('clients.urls', namespace='clients')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
	url(r'^accounts/login/$', views.authentication, name='authentication'),
	url(r'^registered/$', views.registered, name='registered'),
	url(r'^logout$', auth_views.logout, {'next_page': '/accounts/login'}, name='logout')
]

products/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.ProductList.as_view(), name='home'),
	url(r'^product/(?P<pk>[0-9]+)/$', views.ProductDetail.as_view(), 
		name='detail'),
	url(r'^product/new$', views.ProductCreate.as_view(), name='new'),
	url(r'^product/edit/(?P<pk>[0-9]+)/$', 
		views.ProductUpdate.as_view(), name='edit'),
    url(r'^product/delete/(?P<pk>[0-9]+)/$', 
    	views.ProductDelete.as_view(), name='delete'),
    url(r'^report/pdf$', views.reportPDF, name='reportPDF'),
    url(r'^report/csv$', views.reportCSV, name='reportCSV'),
]

clients/models.py
from __future__ import unicode_literals

from django.db import models

class Client(models.Model):
    name = models.CharField(max_length=255)
    phone = models.IntegerField(unique=True)
    email = models.EmailField(max_length=255, unique=True)
    address = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('id',)

products/models.py
from __future__ import unicode_literals

from django.db import models
from clients.models import Client

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('id',)


class Favorite(models.Model):
    user = models.ForeignKey(Client)
    product = models.ForeignKey(Product)

    class Meta:
        verbose_name = 'Favorite'
        verbose_name_plural = 'Favorites'

    def __str__(self):
        return '%s %s' % (self.user.name, self.product.name)

products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
	class Meta:
		model = Product
		fields = '__all__'

clients/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

def authentication(request):
    if request.method == 'POST':
        action = request.POST.get('action', None)
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)

        if action == 'signup':
            user = User.objects.create_user(username=username, password=password)
            user.save()
            return redirect('/registered')

        elif action == 'login':
            user = authenticate(username=username, password=password)
            login(request, user)
            if request.GET.get('next'):
                return redirect(request.GET['next'])
            else:
                return redirect('/')

    return render(request, 'login.html', {})

def registered(request):
    return render(request, 'registered.html', {})

products/views.py
from django.http import HttpResponse
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from .mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView

from django.core.urlresolvers import reverse_lazy

from .models import Product
from .forms import ProductForm

import os
from datetime import date
from io import BytesIO
from reportlab.lib.pagesizes import A4, cm
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.platypus import Paragraph, Table, TableStyle, Image

import csv

class ProductCreate(LoginRequiredMixin, CreateView):
    model = Product
    success_url = reverse_lazy('products:home')
    fields = ['name', 'description', 'category', 'price', 'image']
    title = Product.name

class ProductList(ListView):
    model = Product

class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product

class ProductUpdate(LoginRequiredMixin, UpdateView):
    model = Product
    success_url = reverse_lazy('products:home')
    fields = ['name', 'description', 'category', 'price', 'image']


class ProductDelete(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('products:home')


@login_required()
def reportPDF(request):
    products = Product.objects.order_by('id')

    #Create The HttpResponse headers with PDF
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="Stock_Report.pdf"'

    #Create the PDF object, using the BytesIO object as it's "file."
    buffer = BytesIO()
    fecha = date.today()
    c = canvas.Canvas(buffer, pagesize=A4)

    #Header
    c.setLineWidth(.3)
    c.setFont('Helvetica', 22)
    c.drawString(30, 750, 'Shoppy')
    c.setFont('Helvetica', 12)
    c.drawString(30, 735, ' Web Store')

    c.setFont('Helvetica-Bold', 12)
    c.drawString(480, 750, fecha.__str__())
    c.line(460,747,560,747)

    #Table Header
    styles = getSampleStyleSheet()
    styleBH = styles["Normal"]
    styleBH.alignment = TA_CENTER
    styleBH.fontSize = 10

    name = Paragraph('''NAME''', styleBH)
    category = Paragraph('''CATEGORY''', styleBH)
    price = Paragraph('''PRICE''', styleBH)

    data = []
    data.append([name, category, price])

    #Table Body
    styleN = styles["BodyText"]
    styleN.alignment =TA_CENTER
    styleN.fontSize = 7

    high = 650
    for product in products:
        this_product = [product.name,
                        product.category,
                        product.price,]
        data.append(this_product)
        high = high -18

    #Table Size
    width, height = A4
    table = Table(data, colWidths=[8 * cm,
                                    6 * cm,
                                    5 * cm,
                                    ])
    table.setStyle(TableStyle([
        ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.teal),
        ('BOX', (0, 0), (-1, -1), 0.25, colors.black),]))

    #PDF Size
    table.wrapOn(c, width, height)
    table.drawOn(c, 30, high)
    c.showPage() #Save Page

    #Save PDF
    c.save()

    #Get the value of BytesIO buffer and write response
    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)

    return response

@login_required()
def reportCSV(request):
    products = Product.objects.order_by('id')
    fecha = date.today()
    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="Stock_Report.csv"'

    writer = csv.writer(response)
    writer.writerow(['Shoppy', 'Web Store', fecha])
    writer.writerow(['NAME', 'CATEGORY', 'PRICE'])

    for product in products:
        writer.writerow([product.name,
                        product.category,
                        product.price,])

    return response

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load staticfiles %}
	<meta charset="UTF-8">
	<title>{% block page_title %}{% endblock %}</title>
	<!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<!-- Compiled and minified CSS -->
  	<link rel="stylesheet" href="{% static 'css/materialize.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
  	<!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
	<header>
		<div class="nav-fixed">
			<nav class="teal lighten-2">
		    	<div class="nav-wrapper">
      				<a href="{% url "products:home" %}" class="brand-logo">Shoppy</a>
      				<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      				<ul class="right hide-on-med-and-down">
        				<li>
        					{% if user.is_authenticated %}
        						<a href="#!">{{user.username}}</a>
        					{% else %}
        						<a href="{% url 'clients:authentication' %}">Login</a>
        					{% endif %}
        				</li>
                <li>
                  {% if user.is_authenticated %}
                  <a href="{% url 'products:reportCSV' %}">CSV</a>
                  {% endif %}
                </li>
                <li>
                  {% if user.is_authenticated %}
                  <a href="{% url 'products:reportPDF' %}">PDF</a>
                  {% endif %}
                </li>
        				<li>
							{% if user.is_authenticated %}
        						<a href="{% url 'clients:logout' %}">
        							Logout
        						</a>

        					{% endif %}

        				</li>
                
      				</ul>
      				<ul class="side-nav" id="mobile-demo">

        				<li>
        					{% if user.is_authenticated %}
        						<a href="#!">{{user.username}}</a>
        					{% else %}
        						<a href="{% url 'clients:authentication' %}">Login</a>
        					{% endif %}
        				</li>
                <li>
                  {% if user.is_authenticated %}
                  <a href="{% url 'products:reportPDF' %}">PDF</a>
                  {% endif %}
                </li>
                <li>
                  {% if user.is_authenticated %}
                  <a href="{% url 'products:reportCSV' %}">CSV</a>
                  {% endif %}
                </li>
        				<li>
							    {% if user.is_authenticated %}
        						<a href="{% url 'clients:logout' %}">
        							Logout
        						</a>
        					{% endif %}
        				</li>
      				</ul>
    			</div>
  			</nav>
		</div>
	</header>
	
	{% block content %}{% endblock %}

	<footer class="page-footer teal lighten-2">
        <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Shoppy</h5>
                <p class="grey-text text-lighten-4">Django Project.</p>
              </div>
              	<div class="col l4 offset-l2 s12">
                	<!-- <h5 class="white-text">Links</h5>
	                <ul>
	                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
	                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
	                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
	                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
	                </ul> -->
              	</div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
            © 2016 Jhonbeltran
            <a class="grey-text text-lighten-4 right" href="#!"></a>
            </div>
        </div>
    </footer>
	<!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <!-- Compiled and minified JavaScript -->
  	<script src="{% static 'js/materialize.js' %}"></script>
  	<script src="{% static 'js/code.js' %}"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block page_title %}
	{{ title }}
{% endblock %}
{% block content %}
	<div class="container">
		<div class="row center">
			<h3 class="teal-text">¿Buscas un nuevo dispositivo o accesorio?</h3>
		</div>
		<div class="row center">
			<a href="{% url 'products:new_product' %}" class="flow-text teal-text">Agregar nuevo producto</a>
			<h3 class="flow-text">A continuación podrás ver nuestros productos:</h3>

			{% for product in products %}
				<li>
					<div class="chip">
						<a href="{% url 'products:product_detail' product.pk %}">
							{{ product.name }}
						</a>
						<img src="{{ product.image.url }}" alt="">
					</div>
				</li>
			{% endfor %}
		</div>

	</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block page_title %}
	{{ title }}
{% endblock %}
{% block content %}
	<div class="container">
		<div class="row center">
			<!-- Login -->
			<div class="col s12 m6">
				<h3 class="teal-text">¿Ya tienes una cuenta?</h3>
				<form action="" method="post">
					{% csrf_token %}
					<input type="hidden" name="action" value="login">

					<input type="text" name="username">
					<input type="password" name="password">
					<button class="btn waves-effect waves-light" type="submit">
						Login
		    			<i class="material-icons right">send</i>
		  			</button>
		  		</form>
			</div>
			<!-- Signup -->
			<div class="col s12 m6">
				<h3 class="blue-grey-text">Registrate es gratis</h3>
				<form action="" method="post">
					{% csrf_token %}
					<input type="hidden" name="action" value="signup">

					<input type="text" name="username">
					<input type="password" name="password">
					<button class="btn waves-effect waves-light blue-grey" type="submit">
						Signup
		    			<i class="material-icons right">send</i>
		  			</button>
		  		</form>
			</div>
		</div>
		
	</div>
{% endblock %}

templates/new_product.html
{% extends "base.html" %}
{% block page_title %}
	{{ title }}
{% endblock %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col s12">
				<h2 class="center">Agrega un nuevo producto</h2>
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{{ form }}
				
			</div>
		</div>
		<div class="row center">
			<button class="btn waves-effect waves-light" type="submit" name="action">Submit
		    	<i class="material-icons right">send</i>
		  	</button>
		  	</form>
		</div>
	</div>
	
	
{% endblock %}

templates/products/product_confirm_delete.html
{% extends "base.html" %}
{% block page_title %}
	{{ title }}
{% endblock %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col s12">
				
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					<p class="flow-text center">
						¿Realmente que deseas borrar el producto "{{ object }}"?
					</p>
				
			</div>
		</div>
		<div class="row center">
			<a class="btn red waves-effect waves-light" href="{% url "products:home"%}">
		  		Espera, no lo borres
		  		<i class="material-icons right">clear</i>
		  	</a>
			<button class="btn green waves-effect waves-light" type="submit" value="Submit">Si, borralo de una vez
		    	<i class="material-icons right">done</i>
		  	</button>
		  	
		  	</form>
		</div>
	</div>
	
	
{% endblock %}

templates/products/product_detail.html
{% extends "base.html" %}
{% block page_title %}
	{{ product.name }}
{% endblock %}
{% block content %}
	<div class="container">
		<div class="row center">
			<h3 class="teal-text">{{ product.name }}</h3>
		</div>
		<div class="row center">
			<div class="col s12 m6">
				<p class="flow-text">
					{{ product.description }}
				</p>
				<p class="flow-text">
					{{ product.price }}
				</p>
			</div>
			<div class="col s12 m6">
				<img src="{{ product.image.url }}" alt="">
			</div>

		</div>

	</div>
{% endblock %}

templates/products/product_form.html
{% extends "base.html" %}
{% block page_title %}
	{{ title }}
{% endblock %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col s12">
				
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{{ form }}
				
			</div>
		</div>
		<div class="row center">
			<button class="btn waves-effect waves-light" type="submit" value="Save">Submit
		    	<i class="material-icons right">send</i>
		  	</button>
		  	</form>
		</div>
	</div>
	
	
{% endblock %}

templates/products/product_list.html
{% extends "base.html" %}
{% block page_title %}
	{{ title }}
{% endblock %}
{% block content %}
	<div class="container">
		<div class="row center">
			<h3 class="teal-text">¿Buscas un nuevo dispositivo o accesorio?</h3>
		</div>
		<div class="row center">
			<a href="{% url 'products:new' %}" class="flow-text teal-text">Agregar nuevo producto</a>
			<h3 class="flow-text">A continuación podrás ver nuestros productos:</h3>

			{% for product in object_list %}
				<li>
					<div class="chip">
						<a href="{% url "products:detail" product.id %}">
							{{ product.name }}
						</a>
						<img src="{{ product.image.url }}" alt="">
					</div>
					<a href="{% url "products:edit" product.id %}">Editar</a> | 
                	<a href="{% url "products:delete" product.id %}">Borrar</a> 
				</li>
			{% endfor %}
		</div>

	</div>
{% endblock %}

templates/registered.html
{% extends "base.html" %}
{% block page_title %}
	{{ title }}
{% endblock %}
{% block content %}
	<div class="container">
		<div class="row center">
			<h3 class="teal-text">Te has registrado con éxito</h3>
		</div>
		<div class="row center">
			<a href="{% url 'clients:authentication' %}" class="flow-text">ingresar</a>
		</div>

	</div>
{% endblock %}